public enum GermanState: CaseIterable {
    /// Baden-Württemberg
    case bw
    /// Bayern
    case by
    /// Berlin
    case be
    /// Brandenburg
    case bb
    /// Bremen
    case hb
    /// Hamburg
    case hh
    /// Hessen
    case he
    /// Mecklenburg-Vorpommern
    case mv
    /// Niedersachsen
    case ni
    /// Nordrhein-Westfalen
    case nw
    /// Rheinland-Pfalz
    case rp
    /// Saarland
    case sl
    /// Sachsen
    case sn
    /// Sachsen-Anhalt
    case st
    /// Schleswig-Holstein
    case sh
    /// Thüringen
    case th
}
