#if !canImport(ObjectiveC)
import XCTest

extension FeiertageTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FeiertageTests = [
        ("testNewYears", testNewYears),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FeiertageTests.__allTests__FeiertageTests),
    ]
}
#endif
